name: Build Push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Get Current Version
      run: |
        PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        ::set-output name=parsegrind_version::$PROJECT_VERSION
      outputs:
        parsegrind_version:
            description: 'The version of Parsegrind'



